# .github/workflows/build.yml
name: Build and Push Warp Docker Image

on:
  # Trigger the build on any push to the main branch
  push:
    branches:
      - main
  # Allow manual triggering from the GitHub UI
  workflow_dispatch:

jobs:
  build-and-push:
    # This job will run on any available self-hosted runner
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        # This action sets up the Docker build environment
        uses: docker/setup-buildx-action@v3

      - name: Build image and load to local Docker
        # This step builds the image from the Dockerfile and loads it into the
        # runner's local Docker daemon so we can run it in the next step.
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # Important: Load image to local daemon instead of pushing
          tags: local-warp:latest

      - name: Extract Warp Version from built image
        id: get_version
        # THIS IS THE CORRECTED STEP:
        # We use `--entrypoint warp-cli` to bypass the custom entrypoint.sh
        # script and run the `warp-cli --version` command directly.
        run: |
          VERSION=$(docker run --rm --entrypoint warp-cli local-warp:latest --version | awk '{print $2}')
          echo "Extracted version: $VERSION"
          echo "WARP_VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push to GHCR
        # This final step tags the locally built image with the correct registry
        # name and version, then pushes both tags.
        run: |
          VERSION=${{ steps.get_version.outputs.WARP_VERSION }}
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          echo "Tagging ghcr.io/$REPO_LOWER:latest"
          docker tag local-warp:latest ghcr.io/$REPO_LOWER:latest
          
          echo "Tagging ghcr.io/$REPO_LOWER:$VERSION"
          docker tag local-warp:latest ghcr.io/$REPO_LOWER:$VERSION
          
          echo "Pushing tags to GHCR..."
          docker push ghcr.io/$REPO_LOWER:latest
          docker push ghcr.io/$REPO_LOWER:$VERSION
